name: Playwright Tests

on: [push, pull_request]

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências do projeto
        run: npm install

      - name: Instalar Playwright e dependências do sistema
        run: npx playwright install --with-deps

      - name: Rodar testes de UI
        run: npm run test:ui

      - name: Salvar relatório de UI
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-ui-report
          path: playwright-report
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de API
        run: npm run test:api

      - name: Salvar relatório de API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-api-report
          path: playwright-report
